//
//  AirportsModel.swift
//  predictiveairportpickup
//
//  Created by Ben Burns on 4/6/22.
//

import Foundation

class AirportsModel: ObservableObject {
    @Published var searchText = ""
    
    var allAirports: [String]
    var filteredAirports: [String] = [String]()
    
    init() {
        self.allAirports = airports.sorted()
        self.filteredAirports = allAirports
    }
    
    var airports: [String] = [
        "Errors (ERR)", //REMOVE THIS
        "Birmingham International Airport (BHM)",
        "Dothan Regional Airport (DHN)",
        "Huntsville International Airport (HSV)",
        "Mobile (MOB)",
        "Montgomery (MGM)",
        "Anchorage International Airport (ANC)",
        "Fairbanks International Airport (FAI)",
        "Juneau International Airport (JNU)",
        "Flagstaff (FLG)",
        "Phoenix Sky Harbor International Airport (PHX)",
        "Tucson International Airport (TUS)",
        "Yuma International Airport (YUM)",
        "Fayetteville (Arkansas) (FYV)",
        "Little Rock National Airport (LIT)",
        "Northwest Arkansas Regional Airport (XNA)",
        "Burbank (BUR)",
        "Fresno (FAT)",
        "Long Beach (LGB)",
        "Los Angeles International Airport (LAX)",
        "Oakland (OAK)",
        "Ontario (ONT)",
        "Palm Springs (PSP)",
        "Sacramento (SMF)",
        "San Diego (SAN)",
        "San Francisco International Airport (SFO)",
        "San Jose (SJC)",
        "Santa Ana (SNA)",
        "Aspen (ASE)",
        "Colorado Springs (COS)",
        "Denver International Airport (DEN)",
        "Grand Junction (GJT)",
        "Pueblo (PUB)",
        "Hartford (BDL)",
        "Tweed New Haven (HVN)",
        "Dulles International Airport (IAD)",
        "Washington National Airport (DCA)",
        "Daytona Beach (DAB)",
        "Fort Lauderdale-Hollywood International Airport (FLL)",
        "Fort Meyers (RSW)",
        "Jacksonville (JAX)",
        "Key West International Airport (EYW)",
        "Miami International Airport (MIA)",
        "Orlando (MCO)",
        "Pensacola (PNS)",
        "St. Petersburg (PIE)",
        "Sarasota (SRQ)",
        "Tampa (TPA)",
        "West Palm Beach (PBI)",
        "Panama City-Bay County International Airport (PFN)",
        "Augusta (Georgia) (AGS)",
        "Savannah (SAV)",
        "Hilo (ITO)",
        "Honolulu International Airport (HNL)",
        "Kahului (OGG)",
        "Kailua (KOA)",
        "Lihue (LIH)",
        "Boise (BOI)",
        "Chicago Midway Airport (MDW)",
        "Chicago O'Hare International Airport Airport (ORD)",
        "Moline (MLI)",
        "Peoria (PIA)",
        "Evansville (EVV)",
        "Fort Wayne (FWA)",
        "Indianapolis International Airport (IND)",
        "South Bend (SBN)",
        "Cedar Rapids (CID)",
        "Des Moines (DSM)",
        "Wichita (ICT)",
        "Lexington (LEX)",
        "Louisville (SDF)",
        "Baton Rouge (BTR)",
        "New Orleans International Airport (MSY)",
        "Shreveport (SHV)",
        "Augusta (Maine) (AUG)",
        "Bangor (BGR)",
        "Portland (PWM)",
        "Baltimore (BWI)",
        "Logan International Airport (BOS)",
        "Hyannis (HYA)",
        "Nantucket (ACK)",
        "Worcester (ORH)",
        "Battlecreek (BTL)",
        "Detroit Metropolitan Airport (DTW)",
        "Detroit (DET)",
        "Flint (FNT)",
        "Grand Rapids (GRR)",
        "Kalamazoo-Battle Creek International Airport (AZO)",
        "Lansing (LAN)",
        "Saginaw (MBS)",
        "Duluth (DLH)",
        "Minneapolis/St.Paul International Airport (MSP)",
        "Rochester (Minnesota) (RST)",
        "Gulfport (GPT)",
        "Jackson (JAN)",
        "Kansas City (MCI)",
        "Lambert International Airport (STL)",
        "Springfield (SGF)",
        "Billings (BIL)",
        "Lincoln (LNK)",
        "Omaha (OMA)",
        "Las Vegas McCarran International Airport (LAS)",
        "Reno-Tahoe International Airport (RNO)",
        "Manchester (MHT)",
        "Atlantic City International Airport (ACY)",
        "Newark International Airport (EWR)",
        "Trenton (TTN)",
        "Albuquerque International Airport (ABQ)",
        "Alamogordo (ALM)",
        "Albany International Airport (ALB)",
        "Buffalo (BUF)",
        "Islip (ISP)",
        "John F Kennedy International Airport (JFK)",
        "La Guardia Airport (LGA)",
        "Newburgh (SWF)",
        "Rochester (New York) (ROC)",
        "Syracuse (SYR)",
        "Westchester (HPN)",
        "Asheville (AVL)",
        "Charlotte/Douglas International Airport (CLT)",
        "Fayetteville (North Carolina) (FAY)",
        "Greensboro (GSO)",
        "Raleigh (RDU)",
        "Winston-Salem (INT)",
        "Bismark (BIS)",
        "Fargo (FAR)",
        "Akron (CAK)",
        "Cincinnati (CVG)",
        "Cleveland (CLE)",
        "Columbus (CMH)",
        "Dayton (DAY)",
        "Toledo (TOL)",
        "Oklahoma City (OKC)",
        "Tulsa (TUL)",
        "Eugene (EUG)",
        "Portland International Airport (PDX)",
        "Hillsboro Airport (HIO)",
        "Salem (SLE)",
        "Allentown (ABE)",
        "Erie (ERI)",
        "Harrisburg (MDT)",
        "Philadelphia (PHL)",
        "Pittsburgh (PIT)",
        "Scranton (AVP)",
        "Rhode Island T.F. Green Airport (PVD)",
        "Charleston (SC) (CHS)",
        "Columbia (CAE)",
        "Greenville (GSP)",
        "Myrtle Beach (MYR)",
        "Pierre (PIR)",
        "Rapid City (RAP)",
        "Sioux Falls (FSD)",
        "Bristol (TRI)",
        "Chattanooga (CHA)",
        "Knoxville (TYS)",
        "Memphis (MEM)",
        "Nashville (BNA)",
        "Amarillo (AMA)",
        "Austin Bergstrom International Airport (AUS)",
        "Corpus Christi (CRP)",
        "Dallas Love Field Airport (DAL)",
        "Dallas/Fort Worth International Airport (DFW)",
        "El Paso (ELP)",
        "William B Hobby Airport (Houston) (HOU)",
        "George Bush Intercontinental Airport (Houston) (IAH)",
        "Lubbock (LBB)",
        "Midland (MAF)",
        "San Antonio International Airport (SAT)",
        "Salt Lake City (SLC)",
        "Burlington (BTV)",
        "Montpelier (MPV)",
        "Rutland (RUT)",
        "Dulles (IAD)",
        "Newport News (PHF)",
        "Norfolk (ORF)",
        "Richmond (RIC)",
        "Roanoke (ROA)",
        "Tri-Cities Airport (PSC)",
        "Seattle-Tacoma International Airport (SEA)",
        "Spokane International Airport (GEG)",
        "West Virginia International Yeager Airport (CRW)",
        "Clarksburg (CKB)",
        "Huntington Tri-State Airport (HTS)",
        "Green Bay (GRB)",
        "Madison (MSN)",
        "Milwaukee (MKE)",
        "Casper (CPR)",
        "Cheyenne (CYS)",
        "Jackson Hole (JAC)",
        "Rock Springs (RKS)"
    ]
    
    
    let airportsMapping: [String: String] = [
        "Errors (ERR)": "ERR", //REMOVE THIS
        "Birmingham International Airport (BHM)": "BHM",
        "Dothan Regional Airport (DHN)": "DHN",
        "Huntsville International Airport (HSV)": "HSV",
        "Mobile (MOB)": "MOB",
        "Montgomery (MGM)": "MGM",
        "Anchorage International Airport (ANC)": "ANC",
        "Fairbanks International Airport (FAI)": "FAI",
        "Juneau International Airport (JNU)": "JNU",
        "Flagstaff (FLG)": "FLG",
        "Phoenix Sky Harbor International Airport (PHX)": "PHX",
        "Tucson International Airport (TUS)": "TUS",
        "Yuma International Airport (YUM)": "YUM",
        "Fayetteville (Arkansas) (FYV)": "FYV",
        "Little Rock National Airport (LIT)": "LIT",
        "Northwest Arkansas Regional Airport (XNA)": "XNA",
        "Burbank (BUR)": "BUR",
        "Fresno (FAT)": "FAT",
        "Long Beach (LGB)": "LGB",
        "Los Angeles International Airport (LAX)": "LAX",
        "Oakland (OAK)": "OAK",
        "Ontario (ONT)": "ONT",
        "Palm Springs (PSP)": "PSP",
        "Sacramento (SMF)": "SMF",
        "San Diego (SAN)": "SAN",
        "San Francisco International Airport (SFO)": "SFO",
        "San Jose (SJC)": "SJC",
        "Santa Ana (SNA)": "SNA",
        "Aspen (ASE)": "ASE",
        "Colorado Springs (COS)": "COS",
        "Denver International Airport (DEN)": "DEN",
        "Grand Junction (GJT)": "GJT",
        "Pueblo (PUB)": "PUB",
        "Hartford (BDL)": "BDL",
        "Tweed New Haven (HVN)": "HVN",
        "Dulles International Airport (IAD)": "IAD",
        "Washington National Airport (DCA)": "DCA",
        "Daytona Beach (DAB)": "DAB",
        "Fort Lauderdale-Hollywood International Airport (FLL)": "FLL",
        "Fort Meyers (RSW)": "RSW",
        "Jacksonville (JAX)": "JAX",
        "Key West International Airport (EYW)": "EYW",
        "Miami International Airport (MIA)": "MIA",
        "Orlando (MCO)": "MCO",
        "Pensacola (PNS)": "PNS",
        "St. Petersburg (PIE)": "PIE",
        "Sarasota (SRQ)": "SRQ",
        "Tampa (TPA)": "TPA",
        "West Palm Beach (PBI)": "PBI",
        "Panama City-Bay County International Airport (PFN)": "PFN",
        "Augusta (Georgia) (AGS)": "AGS",
        "Savannah (SAV)": "SAV",
        "Hilo (ITO)": "ITO",
        "Honolulu International Airport (HNL)": "HNL",
        "Kahului (OGG)": "OGG",
        "Kailua (KOA)": "KOA",
        "Lihue (LIH)": "LIH",
        "Boise (BOI)": "BOI",
        "Chicago Midway Airport (MDW)": "MDW",
        "Chicago O'Hare International Airport Airport (ORD)": "ORD",
        "Moline (MLI)": "MLI",
        "Peoria (PIA)": "PIA",
        "Evansville (EVV)": "EVV",
        "Fort Wayne (FWA)": "FWA",
        "Indianapolis International Airport (IND)": "IND",
        "South Bend (SBN)": "SBN",
        "Cedar Rapids (CID)": "CID",
        "Des Moines (DSM)": "DSM",
        "Wichita (ICT)": "ICT",
        "Lexington (LEX)": "LEX",
        "Louisville (SDF)": "SDF",
        "Baton Rouge (BTR)": "BTR",
        "New Orleans International Airport (MSY)": "MSY",
        "Shreveport (SHV)": "SHV",
        "Augusta (Maine) (AUG)": "AUG",
        "Bangor (BGR)": "BGR",
        "Portland (PWM)": "PWM",
        "Baltimore (BWI)": "BWI",
        "Logan International Airport (BOS)": "BOS",
        "Hyannis (HYA)": "HYA",
        "Nantucket (ACK)": "ACK",
        "Worcester (ORH)": "ORH",
        "Battlecreek (BTL)": "BTL",
        "Detroit Metropolitan Airport (DTW)": "DTW",
        "Detroit (DET)": "DET",
        "Flint (FNT)": "FNT",
        "Grand Rapids (GRR)": "GRR",
        "Kalamazoo-Battle Creek International Airport (AZO)": "AZO",
        "Lansing (LAN)": "LAN",
        "Saginaw (MBS)": "MBS",
        "Duluth (DLH)": "DLH",
        "Minneapolis/St.Paul International Airport (MSP)": "MSP",
        "Rochester (Minnesota) (RST)": "RST",
        "Gulfport (GPT)": "GPT",
        "Jackson (JAN)": "JAN",
        "Kansas City (MCI)": "MCI",
        "Lambert International Airport (STL)": "STL",
        "Springfield (SGF)": "SGF",
        "Billings (BIL)": "BIL",
        "Lincoln (LNK)": "LNK",
        "Omaha (OMA)": "OMA",
        "Las Vegas McCarran International Airport (LAS)": "LAS",
        "Reno-Tahoe International Airport (RNO)": "RNO",
        "Manchester (MHT)": "MHT",
        "Atlantic City International Airport (ACY)": "ACY",
        "Newark International Airport (EWR)": "EWR",
        "Trenton (TTN)": "TTN",
        "Albuquerque International Airport (ABQ)": "ABQ",
        "Alamogordo (ALM)": "ALM",
        "Albany International Airport (ALB)": "ALB",
        "Buffalo (BUF)": "BUF",
        "Islip (ISP)": "ISP",
        "John F Kennedy International Airport (JFK)": "JFK",
        "La Guardia Airport (LGA)": "LGA",
        "Newburgh (SWF)": "SWF",
        "Rochester (New York) (ROC)": "ROC",
        "Syracuse (SYR)": "SYR",
        "Westchester (HPN)": "HPN",
        "Asheville (AVL)": "AVL",
        "Charlotte/Douglas International Airport (CLT)": "CLT",
        "Fayetteville (North Carolina) (FAY)": "FAY",
        "Greensboro (GSO)": "GSO",
        "Raleigh (RDU)": "RDU",
        "Winston-Salem (INT)": "INT",
        "Bismark (BIS)": "BIS",
        "Fargo (FAR)": "FAR",
        "Akron (CAK)": "CAK",
        "Cincinnati (CVG)": "CVG",
        "Cleveland (CLE)": "CLE",
        "Columbus (CMH)": "CMH",
        "Dayton (DAY)": "DAY",
        "Toledo (TOL)": "TOL",
        "Oklahoma City (OKC)": "OKC",
        "Tulsa (TUL)": "TUL",
        "Eugene (EUG)": "EUG",
        "Portland International Airport (PDX)": "PDX",
        "Hillsboro Airport (HIO)": "HIO",
        "Salem (SLE)": "SLE",
        "Allentown (ABE)": "ABE",
        "Erie (ERI)": "ERI",
        "Harrisburg (MDT)": "MDT",
        "Philadelphia (PHL)": "PHL",
        "Pittsburgh (PIT)": "PIT",
        "Scranton (AVP)": "AVP",
        "Rhode Island T.F. Green Airport (PVD)": "PVD",
        "Charleston (SC) (CHS)": "CHS",
        "Columbia (CAE)": "CAE",
        "Greenville (GSP)": "GSP",
        "Myrtle Beach (MYR)": "MYR",
        "Pierre (PIR)": "PIR",
        "Rapid City (RAP)": "RAP",
        "Sioux Falls (FSD)": "FSD",
        "Bristol (TRI)": "TRI",
        "Chattanooga (CHA)": "CHA",
        "Knoxville (TYS)": "TYS",
        "Memphis (MEM)": "MEM",
        "Nashville (BNA)": "BNA",
        "Amarillo (AMA)": "AMA",
        "Austin Bergstrom International Airport (AUS)": "AUS",
        "Corpus Christi (CRP)": "CRP",
        "Dallas Love Field Airport (DAL)": "DAL",
        "Dallas/Fort Worth International Airport (DFW)": "DFW",
        "El Paso (ELP)": "ELP",
        "William B Hobby Airport (Houston) (HOU)": "HOU",
        "George Bush Intercontinental Airport (Houston) (IAH)": "IAH",
        "Lubbock (LBB)": "LBB",
        "Midland (MAF)": "MAF",
        "San Antonio International Airport (SAT)": "SAT",
        "Salt Lake City (SLC)": "SLC",
        "Burlington (BTV)": "BTV",
        "Montpelier (MPV)": "MPV",
        "Rutland (RUT)": "RUT",
        "Dulles (IAD)": "IAD",
        "Newport News (PHF)": "PHF",
        "Norfolk (ORF)": "ORF",
        "Richmond (RIC)": "RIC",
        "Roanoke (ROA)": "ROA",
        "Tri-Cities Airport (PSC)": "PSC",
        "Seattle-Tacoma International Airport (SEA)": "SEA",
        "Spokane International Airport (GEG)": "GEG",
        "West Virginia International Yeager Airport (CRW)": "CRW",
        "Clarksburg (CKB)": "CKB",
        "Huntington Tri-State Airport (HTS)": "HTS",
        "Green Bay (GRB)": "GRB",
        "Madison (MSN)": "MSN",
        "Milwaukee (MKE)": "MKE",
        "Casper (CPR)": "CPR",
        "Cheyenne (CYS)": "CYS",
        "Jackson Hole (JAC)": "JAC",
        "Rock Springs (RKS)": "RKS"
    ]
}
